# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: kuri__v1
networks:
  - id: 8453
    start_block: 35219463
    contracts:
      - name: KuriCoreFactory
        address:
          - 0x4cd6cb26cf8599b3ea0c249ba5dd5ece46e01d9c
        handler: src/EventHandlers.ts
        events:
          - event: CurrencyRemoved(address caller, address currencyRemoved)
          - event: KeyHashUpdated(bytes32 newKeyHash, bytes32 oldKeyHash)
          - event: KuriMarketDeployed(address indexed caller, address indexed marketAddress, uint8 intervalType, uint256 timestamp, bool wannabeMember, address circleCurrencyAddress)
          - event: NewCircleCurrencyAdded(address caller, address newCurrencyAddress)
          - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
          - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
          - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
          - event: VRFCoordinatorUpdated(address newCoordinator, address oldCoordinator)

      - name: KuriCore
        abi_file_path: abis/KuriCore.json
        handler: src/EventHandlers.ts
        events:
          - event: BeefyVaultDeposit(address indexed user, uint16 indexed intervalIndex, address indexed vaultAddress, uint256 shareAmount, uint256 kuriAmount, uint256 timestamp)
          - event: BeefyVaultWithdraw(address indexed user, address indexed vaultAddress, uint256 shareAmount, uint256 withdrawAmount, uint256 timestamp)
          - event: CoordinatorSet(address vrfCoordinator)
          - event: KuriInitFailed(address creator, uint64 kuriAmount, uint16 totalParticipantsCount, uint8 state)
          - event: KuriInitialised((address,uint64,uint16,uint16,uint24,uint48,uint48,uint48,uint48,uint48,uint8,uint8) _kuriData)
          - event: KuriSlotClaimed(address user, uint64 timestamp, uint64 kuriAmount, uint16 intervalIndex)
          - event: MarketVRFSubscriptionDone(uint256 subscriptionId, address subscriber)
          - event: MembershipRequested(address user, uint256 timestamp)
          - event: OwnershipTransferRequested(address indexed from, address indexed to)
          - event: OwnershipTransferred(address indexed from, address indexed to)
          - event: RaffleWinnerSelected(uint16 intervalIndex, uint16 winnerIndex, address winnerAddress, uint48 winnerTimestamp, uint256 requestId)
          - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
          - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
          - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
          - event: UserAccepted(address user, address caller, uint16 _totalActiveParticipantsCount)
          - event: UserDeposited(address user, uint256 userIndex, uint256 intervalIndex, uint64 amountDeposited, uint48 depositTimestamp)
          - event: UserFlagged(address user, uint16 intervalIndex)
          - event: UserRejected(address user, address caller)

unordered_multichain_mode: true
